### ISSUE TITLE
Is this process right? ( sub issue : error  , dimensions and etc..)  

### ISSUE THREAD

**Issue by CAI23sbP** [Arena-Rosnav/arena-evaluation#1]
Hi @ReykCS ! 
I wanted to evaluation scenarios, so had done this work. Could i lend your hand for check if my actions were correct?.
Additionally i have gifts(?) for you.(these are actually questions)
References are from[ link](https://arena-rosnav.readthedocs.io/en/latest/user_guides/usage/) and [link](https://github.com/Arena-Rosnav/arena-evaluation)
1. launch roslaunch arena_bringup start_arena.launch record_data:=true
2. python get_metrics.py --dir {$record_data_path} 
    -> There was a issue about "cmd_vel.csv" which was sometimes recorded empty record. example : time, data (80600000086.0,"[ ]") 
,could you explain why?. 

3. I made a schema.yml file by being followed up your sample file.
     ->Could you explain about this parameter?. I saw your explanation, but it is hard to understand definitely.... 

5. python  create_plots.py {$schema.yml_path}
   -> Unfortunately, there is a issue about "ResultPlotter".
   that issue is "it has no arguments to ResultPotter()", so what can i do this?

P.s : i guess that i should integrate old package and new one, is that right?

**Comment by ReykCS** [comment]
Hey,
unfortunately, all the documentation you referred too were deprecated too. I updated the readme for this repo a little bit and at least removed everything that is not current. I also pushed some commits to resolve some of your issues with 4.

I can't explain why cmd_vel contains empty values. It could well be that your setup is not keeping up with the desired update rate and therefore messages are sent too late sometimes. Try to reduce the update rate in `arena_launch/params/flatland_deploy`.

The plot declaration file gives you a good way of creating multiple different plots without writing a single line of code. Unfortunately, I don't know exactly which parameter you mean but the repo contains a real declaration file now which I used days ago to create some plots. Hopefully, this helps you with your problem.

And you don't need any old packages for using this. It is completely independent from them.

**Comment by CAI23sbP** [comment]
Oh! thank you @ReykCS ! your answer is very helpful to me :>
I have two small issues.

1. in "get_metric.py(in recent version) ". 
When i launched get_metric.py, it sometimes made a "ZeroDivisionError: division by zero".

!!!Here is a error script!!!
`  File "get_metrics.py", line 381, in <module>
    Metrics(arguments.dir)
  File "get_metrics.py", line 84, in __init__
    episode_data[i] = self.analyze_episode(current_episode, i)
  File "get_metrics.py", line 130, in analyze_episode
    "angle_over_length": self.get_angle_over_length(path_length, positions),
  File "get_metrics.py", line 170, in get_angle_over_length
    return total_yaw / path_length
ZeroDivisionError: division by zero ` 

I checked if there is any empty list or something similar in dataset, but that was not exist. could you see this issue?
Here is a dataset
[cmd_vel.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10789005/cmd_vel.csv)
[episode.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10789006/episode.csv)
[odom.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10789007/odom.csv) -> I think it is make a issue.
[scan.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10789008/scan.csv)
[start_goal.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10789009/start_goal.csv)

--> this issue similar about this? 
> I can't explain why cmd_vel contains empty values. It could well be that your setup is not keeping up with the desired update rate and therefore messages are sent too late sometimes. Try to reduce the update rate in arena_launch/params/flatland_deploy.

2. in "get_metric.py(in recent version) ".
Sometimes get_metric.py made empty lists. (local planner dwa) 
Here is a dataset
[cmd_vel.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10788982/cmd_vel.csv)
[episode.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10788983/episode.csv)
[metrics.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10788984/metrics.csv) -> You can see empty lists in this data
[odom.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10788985/odom.csv)
[scan.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10788987/scan.csv)
[start_goal.csv](https://github.com/Arena-Rosnav/arena-evaluation/files/10788988/start_goal.csv)

could you see this issue too?
These issues need to re-record?(=These issues are unavoidable issues?)
 

P.s :
1.  what is a get_position_for_collision in get_metrics.py? there is no output in metrics. Is it part of future task? (to draw path and collision) 

2. what is this [src](https://github.com/Arena-Rosnav/arena-rosnav/blob/master/utils/eval/src/run_evals.py)? could you explain what is different between arena-evaluation pkg and this [src](https://github.com/Arena-Rosnav/arena-rosnav/blob/master/utils/eval/src/run_evals.py)? -> i think that it is a vestige from old version.

**Comment by ReykCS** [comment]
Hey @CAI23sbP ,
i downloaded your data and tested it on my own machine. There was indeed an errors that was mainly caused by very small episode length. The last episode, in your case its the second, is not really executed but always added to the evaluation data. I resolved the issue and small episodes will not be evaluated anymore. After this i create a new plot declaration file and plottet your data successful. For example, i plottet this diagram showing the velocity of your planner over time: [episode_velocity.pdf](https://github.com/Arena-Rosnav/arena-evaluation/files/10797792/episode_velocity.pdf)

I also tested your second dataset and it seems that my fix also resolved this issue. The arrays are not empty anymore and i can plot this data as well. 

I guess you are currently running arena-rosnav with the default resets. By setting the argument "default_resets" you can increase the amount for a better evaluation. You can also create scenario tasks, which can be easily done with our new [webapp](https://app.arena-rosnav.com), although this is still in development and may not work as expected. You should create an account there and the navigate to /tools/scenario/new. There you can select a map for your scenario and set the position of your robot as well as the position of pedestrians. You can then download the file and use it locally by copying it to `task_generator/scenario`.

`get_position_for_collisions` stores the robots position for which a collision was recorded in an array. But you are right, currently this is not used and will be part of a future task. However, you can already plot the path your robot took. But collisions will not be included currently.

This is an old evaluation script running multiple evaluations in a row, which are defined in an [evaluation.yaml](https://github.com/Arena-Rosnav/arena-rosnav/blob/master/utils/eval/src/example/evals_template.yaml). This package is rather outdated and comes from the old project structure. It has to updated and is currently not usable.

**Comment by CAI23sbP** [comment]
Thank you for your quick response and your kindness @ReykCS!, it is amazing to me haha!.
By the way you said that i could create scenario task by [webapp ](https://github.com/Arena-Rosnav/arena-evaluation/issues/app.arena-rosnav.com), but i click this link, there doesn't exist web. could you modify that link?.


I have a few questions. 
1. (get_metrics.py) what is roughness? from your code , i guess that it' mean how much pops up that path in a moment
  here is following your code.
   (1) "calc_triangle_area" -> calculate gaussian triangle area
   (2) "calc_roughness" ->  height of triangle is impacted by square to distinguishable.

2. (get_metrics.py) why do you calculate angle over length? in your code, it calculates accumulation of raw divided by accumulation of distance.  what does it mean???

3. (dimension issue) Could you tell me dimensions about time, velocity, position and path in recorded datasets?

**Comment by ReykCS** [comment]
Hey @CAI23sbP ,

looks like GitHub interpreted it as a relative link. The correct link is [this](https://app.arena-rosnav.com). 

I've now added a table with small explanations of the different metrics to the readme. However, I will explain it to you here in detail: Basically, the roughness describes how much the real path differs from the desired path. It is calculated over three continuous points A, B, and C, whereas A is the prior timestep to B and B is the prior to C. The positions of the timesteps A, B, and C now form a triangle, which area can be easily calculated and is done by the `calc_triangle_area` method. Now the area of the triangle is divided by the distance between points A and C. Therefore, we get a metric for how sharp the movement of the robot was in position B and therefore how "rough" it behaves. 

The angle over length metric describes how much the robot turns over the complete path length. The lower this value the better. This value alone does not mean much but in combination with other metrics one can explain the movement of the robot and if it is capable of moving in a straight line or shaking around a given direction. It is also somehow a measurement of how well the control system of the planner or robot works. 

The time is in nanoseconds. The velocity should be in meters per second. I guess the position and path are still in pixels, which should not be. I have to check this and also convert is to meters.

**Comment by CAI23sbP** [comment]
what a awesome website!. i can't control my excitement !. Thank you so much  @ReykCS.
i will come back with another issues or questions.
